{% set name = "eth-abi" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth_abi-{{ version }}.tar.gz
  sha256: d1bd16a911dd8fe45f1e6ed02099b4fceb8ae9ea741ab11b135cf288ada74a99

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - setuptools
  run:
    - eth-utils >=1.2.0,<2.0.0
    - eth-typing >=2.0.0,<3.0.0
    - parsimonious >=0.8.0,<0.10.0
    - setuptools
    - python >=3.7,<4.0

test:
  imports:
    - eth_abi

about:
  home: https://github.com/ethereum/eth-abi
  summary: 'eth_abi: Python utilities for working with Ethereum ABI definitions, especially encoding and decoding'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
