{% set name = "eth-abi" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eth_abi-{{ version }}.tar.gz
  sha256: 178703fa98c07d8eecd5ae569e7e8d159e493ebb6eeb534a8fe973fbc4e40ef0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - eth-utils >=2.0.0
    - eth-typing >=3.0.0
    - parsimonious >=0.10.0,<0.11.0
    - setuptools


test:
  requires:
    - python {{ python_min }}
  imports:
    - eth_abi

about:
  home: https://github.com/ethereum/eth-abi
  summary: 'eth_abi: Python utilities for working with Ethereum ABI definitions, especially encoding and decoding'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
