{% set name = "eth-abi" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth_abi-{{ version }}.tar.gz
  sha256: c3872e3ac1e9ef3f8c6599aaca4ee536d536eefca63a6892ab937f0560edb656

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - eth-typing >=3.0.0,<4.0.0
    - eth-utils >=2.0.0,<3.0.0
    - parsimonious >=0.8.0,<0.9.0
    - python >=3.6,<4.0

test:
  imports:
    - eth_abi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ethereum/eth-abi
  summary: 'eth_abi: Python utilities for working with Ethereum ABI definitions, especially encoding and decoding'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
