{% set name = "eth-abi" %}
{% set version = "4.0.0b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eth_abi-{{ version }}.tar.gz
  sha256: 0cbd5a854acf101843d3f009b10a8b63050125981211ea4d074a80eb953f97ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - setuptools
  run:
    - eth-typing >=3.0.0
    - eth-utils >=2.0.0
    - parsimonious >=0.8.0,<0.10.0
    - setuptools
    - python >=3.6,<4.0

test:
  imports:
    - eth_abi

about:
  home: https://github.com/ethereum/eth-abi
  summary: 'eth_abi: Python utilities for working with Ethereum ABI definitions, especially encoding and decoding'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - step21
